Train:
  batch_size: 128
  learning_rate: 0.25
  epochs: 50
  # steps: [50, 75]   
  warmup: 5
  reg: 0.001
  momentum: 0.9
  gamma: 0.1
  scheduler: cosine
  min_lr: 0.00001
  optimizer: sgd
  nesterov: True 
  
data:
  save_best: True
  dataset: Food101
  img_size: 64
  output_filename: DenseNet121PrunedTest_PRUNED

mlflow:
  mlflow: True
  experiment_name: Densenet121 Eval
  training_info: Eval testing
  training_title: Densenet121 Eval

pruning:
  prune: True
  prune_unstructured: 0.2
  prune_structured: 0.2